# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: docker

steps:
- task: DockerInstaller@0
  inputs:
   dockerVersion: '24.0.7'
  displayName: 'Install Docker 24.0.7'

- script: |
    docker login -u $(docker_username) -p $(docker_password)
  displayName: 'Run a multi-line script'
