# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: docker

steps:
- task: DockerInstaller@0
  inputs:
   dockerVersion: '24.0.7'
  displayName: 'Install Docker 24.0.7'

- script: |
    docker login -u "${DU}" -p "${DP}"
  displayName: 'Login to dockerhub'
  env:
   DU: $(docker_user)
   DP: $(docker_password)

- script: |
    docker pull nginx
  displayName: 'pull Nginx'

- script: |
    docker tag nginx:latest codehunterseducation/szentpeteri:20241114
    docker tag nginx:latest codehunterseducation/szentpeteri:latest
    docker push codehunterseducation/szentpeteri:20241114
  displayName: 'push own nginx'

- script: |
    docker run -d -p 1234:80 codehunterseducation/szentpeteri:20241114
  displayName: 'start container'

- script: |
    sleep 10
    curl -X GET http://localhost:1234
  displayName: 'run integration test'

- script: |
    docker ps
    docker stop $(docker ps -q)
    docker ps
  displayName: 'check containers run'