# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: dockerPeti

steps:
- task: DockerInstaller@0
  inputs:
   dockerVersion: '24.0.7'
  displayName: 'Install Docker 24.0.7'

- script: |
    docker login -u $(docker_user_peti) -p $(docker_password_peti)
  displayName: 'Run a multi-line script'

- script: |
    docker pull nginx
  displayName: 'Pull Nginx'

- script: |
    docker tag nginx:latest codehunterseducation/borspeter:20241114
    docker push codehunterseducation/borspeter:20241114
  displayName: 'Push own Nginx'

- script: |
    docker run -d -p 1234:80 codehunterseducation/borspeter:20241114
  displayName: 'Start container'

- script: |
    sleep 10
    curl -X GET http://localhost:1234
  displayName: 'Run integration test'

- script: |
    docker ps
  displayName: 'Docker ps'