trigger: none

pr: none
schedules:
  - cron: 0 9 * * 1
    displayName: Weekly Monday Build
    branches:
      include:
        - main
    always: true

pool:
  vmImage: ubuntu-latest

variables:
  - group: szentpeteri

jobs:
  - job: printMyOwnName
    timeoutInMinutes: 50
    cancelTimeoutInMinutes: 10
    steps:
      - script: echo $(szentpeteri_name)
        displayName: "Printing name"
